### ISSUE TITLE
Sond files  >100Mb won't  load

### ISSUE THREAD

**Issue by JoopN** [quippy-git/javamod#7]
For already a long time I have one big music file with a size of 105Mb which won't load. I get at the bottom an error.  Is this your program or is  this something with Java?

**Comment by quippy-git** [comment]
JavaMod has no memory constraints build in, so that might be Java itself (Heap), the Java version used, the amount of main memory... But there might be a workaround for that problem. Can you provide me that file for download so I can test? The full stack trace is helpful to see where it crashes.
Might even not be the size but something completely different. There are many broken files out there, that need special treatment.

**Comment by quippy-git** [comment]
As I never received any update, even after asking a valid question, I have to close that issue.

Helpful information on an issue are
- Exception text or at least an error message - this can be marked and copy from the message line at the bottom of the main window. A better way would be to open a CMD, start the jar there and copy every output.
- the file type in question would help massively (is it a MOD-File, or a ZIP, APE, FLAC, MP3, SID?)
- At least: OS-type and version, Java-Version, JavaMod-Version
- if necessary an upload of the file in question to reproduce the error locally

**Comment by JoopN** [comment]
Hello,

I'm not sure if I can send it to you. There is also something like
royalties. Up to 100Mb not a problem, above problems. 

Thank you,
Joop 

Op Mon, 05 Aug 2024 05:00:51 -0700
Daniel Becker ***@***.***> schreef:

> As I never received any update, even after asking a valid question, I
> have to close that issue.
> 
> Helpful information on an issue are
> - Exception text or at least an error message - this can be marked
> and copy from the message line at the bottom of the main window. A
> better way would be to open a CMD, start the jar there and copy every
> output.
> - the file type in question would help massively (is it a MOD-File,
> or a ZIP, APE, FLAC, MP3, SID?)
> - At least: OS-type and version, Java-Version, JavaMod-Version
> - if necessary an upload of the file in question to reproduce the
> error locally
>

**Comment by quippy-git** [comment]
Most mods shouldn't have any problem with royalty.

However, please do what I said:
- Provide file type or file name
- start CMD (or whatever it is on your OS) and start javamod via `java -jar javamod.jar` - copy & past error message and stack trace. If necessary find out how to redirect error output to a file and send that (like `java -jar javamod.jar > errors.txt 2>&1`)
- what javamod version
- what jdk? JavaMod Help dialog provides necessary infos!
- what OS and what OS version
- amount of main memory

So far I have absolutely nothing to start any investigation on.

**Comment by JoopN** [comment]
Op Tue, 06 Aug 2024 05:07:39 -0700
Daniel Becker ***@***.***> schreef:

> Most mods shouldn't have any problem with royalty.
> 
> However, please do what I said:
> - Provide file type or file name
> - start CMD (or whatever it is on your OS) and start javamod via
> `java -jar javamod.jar` - copy & past error message and stack trace.
> If necessary find out how to redirect error output to a file and send
> that (like `java -jar javamod.jar > errors.txt 2>&1`)
> - what javamod version
> - what jdk? JavaMod Help dialog provides necessary infos!
> - what OS and what OS version
> - amount of main memory
> 
> So far I have absolutely nothing to start any investigation on.
> 
Contents error file:
[PlayThread::run]
java.lang.RuntimeException: de.quippy.mp3.decoder.BitstreamException: Bitstream errorcode 102
	at de.quippy.javamod.multimedia.mp3.MP3Mixer.startPlayback(Unknown Source)
	at de.quippy.javamod.main.gui.PlayThread.run(Unknown Source)
Caused by: de.quippy.mp3.decoder.BitstreamException: Bitstream errorcode 102
	at de.quippy.mp3.decoder.Bitstream.newBitstreamException(Unknown Source)
	at de.quippy.mp3.decoder.Bitstream.readFrame(Unknown Source)
	... 2 more

Info Java:
openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Debian-1deb12u1, mixed mode,
sharing)

Played MP3:
File MP3 115,4Mb

start CMD:
#!/bin/sh

#go to script's directory
progdir=${0%/*} 
cd $progdir

#launch Javamod

#java -Xmx128m -jar javamod.jar 2>javamod-bugs.txt
java -jar javamod.jar 2>javamod-bugs.txt 

Info javamod:
It might help if you can copy the infopage of your program as text so
I can include it here. See included info.jpg

System:
Raspberry Pi 400 with 4Gb

Regards,
Joop

**Comment by quippy-git** [comment]
This error has nothing to do with size but with something unexpected in the MP3 file you try to play - there is something corrupted in that file - so it's a problem in the JLayer MP3 decoder. The MP3-Decoder runs into a problem here. The thing is now, that I have not much I can do without the possibility to debug though that code, which is not mine BTW.

And: No attachment reached me.

BTW: The error code 102 is a general BitStream Error - which is typically a wrapped IOException. Java seems not to be able to read that file properly - for whatever reason.

**Comment by JoopN** [comment]
Op Thu, 08 Aug 2024 06:29:19 -0700
Daniel Becker ***@***.***> schreef:

> This error has nothing to do with size but with something unexpected
> in the MP3 file you try to play - there is something corrupted in
> that file - so it's a problem in the JLayer MP3 decoder. The
> MP3-Decoder runs into a problem here. The thing is now, that I have
> not much I can do without the possibility to debug though that code,
> which is not mine BTW.
> 
> And: No attachment reached me.
> 

Strange, its send with a jpeg file which is the infopage of your
program. May be github don't accept that. 

At first I had a different error. Then I tried something you
suggested and I got the error which I did send to you. The last
days I was trying to find out if it occurs on the same place,
this could be an error in the file. But one time it was right up
front after a few minutes of the file and last day it was playing half
an our and then I got that error. So I can rule out that the file is
damaged in some way. I don't know what the error code means, it looks
to me some kind of buffer problem. There are no problems if the file
is smaller then 100Mb up to now. 

Regards,
Joop

**Comment by quippy-git** [comment]
Then this will be hard to find and I wouldn't expect an error in the file nor the coding. It seems to me, that the pushback buffer of the PushbackInputStream might overflow - but why - and why at different places in the file?
There could be a background process, that interferes with the disc access. On Windows I would suspect a virus scanner - but I guess that you are not using ClamAV.
What you could test is to upgrade to OpenJDK 22 - which should be easily done. JDKs might also have errors. The other thing to try would be to test the playback on a different machine than the Raspi. Maybe your desktop PC or laptop.

**Comment by quippy-git** [comment]
There was no come back on that one. The cause for that error could not be found. As I stream megabytes of radio streams without error - and MP3s are also played back as streams - I would suspect something else but not the coding.
